### ISSUE TITLE
feat: add `isSupported` method

### ISSUE THREAD

**Issue by robingenz** [robingenz/capacitor-badge#8]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to check if the platform supports badges.

**Describe the solution you'd like**
Add a method (e.g. `isSupported`) that checks if badges are supported.

**Describe alternatives you've considered**
No alternative solutions.

**Comment by ptmkenny** [comment]
I'd definitely like to see this feature.

Also, I would suggest changing the error text `Uncaught (in promise) Error: "Badge" plugin is not implemented on android` to something like "is not implemented in this version of Android."  When I first saw the error message, I thought that Badge wouldn't work in Android at all, because there are some Capacitor plugins that work only in iOS and not on Android.

**Comment by robingenz** [comment]
This error message comes from Capacitor and not from this plugin. 
Please make sure that the plugin has been added correctly.
If problems persist, please create a new issue.
